language: java

matrix:
  include:
  - os: linux
    env: CUSTOM_JDK="oraclejdk8"

install:
  - mvn install -Dgpg.skip
script:
  - mvn clean package test
after_success:
  - mvn clean package -Pit-test
  - mvn sonar:sonar -Psonar-apache