server:
  port: 8099

spring:
  application:
    name: tutorials
  rabbitmq:
    host: 111.231.93.42
    port: 5672
    username: root
    password: surick
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017
      database: test
